'use client';

const cards = [
  { name: 'Three Musketeers', image: '/assets/clash-royale/cards/3Musk.webp' },
  { name: 'Archer Queen', image: '/assets/clash-royale/cards/ArcherQueen.webp' },
  { name: 'Archers', image: '/assets/clash-royale/cards/Archers.webp' },
  { name: 'Arrows', image: '/assets/clash-royale/cards/Arrows.webp' },
  { name: 'Baby Dragon', image: '/assets/clash-royale/cards/BabyD.webp' },
  { name: 'Balloon', image: '/assets/clash-royale/cards/Balloon.webp' },
  { name: 'Bandit', image: '/assets/clash-royale/cards/Bandit.webp' },
  { name: 'Barbarian Barrel', image: '/assets/clash-royale/cards/BarbBarrel.webp' },
  { name: 'Barbarian Hut', image: '/assets/clash-royale/cards/BarbHut.webp' },
  { name: 'Barbarians', image: '/assets/clash-royale/cards/Barbs.webp' },
  { name: 'Goblin Barrel', image: '/assets/clash-royale/cards/Barrel.webp' },
  { name: 'Bats', image: '/assets/clash-royale/cards/Bats.webp' },
  { name: 'Battle Healer', image: '/assets/clash-royale/cards/BattleHealer.webp' },
  { name: 'Berserker', image: '/assets/clash-royale/cards/Berserker.webp' },
  { name: 'Bomber', image: '/assets/clash-royale/cards/Bomber.webp' },
  { name: 'Bomb Tower', image: '/assets/clash-royale/cards/BombTower.webp' },
  { name: 'Boss Bandit', image: '/assets/clash-royale/cards/BossBandit.webp' },
  { name: 'Bowler', image: '/assets/clash-royale/cards/Bowler.webp' },
  { name: 'Cannon', image: '/assets/clash-royale/cards/Cannon.webp' },
  { name: 'Cannon Cart', image: '/assets/clash-royale/cards/CannonCart.webp' },
  { name: 'Clone', image: '/assets/clash-royale/cards/Clone.webp' },
  { name: 'Dark Prince', image: '/assets/clash-royale/cards/DarkPrince.webp' },
  { name: 'Dart Goblin', image: '/assets/clash-royale/cards/DartGob.webp' },
  { name: 'Earthquake', image: '/assets/clash-royale/cards/Earthquake.webp' },
  { name: 'Elite Barbarians', image: '/assets/clash-royale/cards/eBarbs.webp' },
  { name: 'Electro Dragon', image: '/assets/clash-royale/cards/eDragon.webp' },
  { name: 'Electro Giant', image: '/assets/clash-royale/cards/ElectroGiant.webp' },
  { name: 'Electro Spirit', image: '/assets/clash-royale/cards/ElectroSpirit.webp' },
  { name: 'Elixir Golem', image: '/assets/clash-royale/cards/ElixirGolem.webp' },
  { name: 'Electro Wizard', image: '/assets/clash-royale/cards/eWiz.webp' },
  { name: 'Executioner', image: '/assets/clash-royale/cards/Exe.webp' },
  { name: 'Fireball', image: '/assets/clash-royale/cards/Fireball.webp' },
  { name: 'Firecracker', image: '/assets/clash-royale/cards/Firecracker.webp' },
  { name: 'Fire Spirit', image: '/assets/clash-royale/cards/FireSpirit.webp' },
  { name: 'Fisherman', image: '/assets/clash-royale/cards/Fisherman.webp' },
  { name: 'Flying Machine', image: '/assets/clash-royale/cards/FlyingMachine.webp' },
  { name: 'Freeze', image: '/assets/clash-royale/cards/Freeze.webp' },
  { name: 'Furnace', image: '/assets/clash-royale/cards/Furnace.webp' },
  { name: 'Royal Ghost', image: '/assets/clash-royale/cards/Ghost.webp' },
  { name: 'Giant', image: '/assets/clash-royale/cards/Giant.webp' },
  { name: 'Giant Skeleton', image: '/assets/clash-royale/cards/GiantSkelly.webp' },
  { name: 'Goblin Gang', image: '/assets/clash-royale/cards/GobGang.webp' },
  { name: 'Goblin Giant', image: '/assets/clash-royale/cards/GobGiant.webp' },
  { name: 'Goblin Hut', image: '/assets/clash-royale/cards/GobHut.webp' },
  { name: 'Goblin Cage', image: '/assets/clash-royale/cards/GoblinCage.webp' },
  { name: 'Goblin Curse', image: '/assets/clash-royale/cards/GoblinCurse.webp' },
  { name: 'Goblin Demolisher', image: '/assets/clash-royale/cards/GoblinDemolisher.webp' },
  { name: 'Goblin Drill', image: '/assets/clash-royale/cards/GoblinDrill.webp' },
  { name: 'Goblin Machine', image: '/assets/clash-royale/cards/GoblinMachine.webp' },
  { name: 'Goblinstein', image: '/assets/clash-royale/cards/Goblinstein.webp' },
  { name: 'Goblins', image: '/assets/clash-royale/cards/Gobs.webp' },
  { name: 'Golden Knight', image: '/assets/clash-royale/cards/GoldenKnight.webp' },
  { name: 'Golem', image: '/assets/clash-royale/cards/Golem.webp' },
  { name: 'Graveyard', image: '/assets/clash-royale/cards/Graveyard.webp' },
  { name: 'Guards', image: '/assets/clash-royale/cards/Guards.webp' },
  { name: 'Heal Spirit', image: '/assets/clash-royale/cards/HealSpirit.webp' },
  { name: 'Hog Rider', image: '/assets/clash-royale/cards/Hog.webp' },
  { name: 'Minion Horde', image: '/assets/clash-royale/cards/Horde.webp' },
  { name: 'Hunter', image: '/assets/clash-royale/cards/Hunter.webp' },
  { name: 'Ice Golem', image: '/assets/clash-royale/cards/IceGolem.webp' },
  { name: 'Ice Spirit', image: '/assets/clash-royale/cards/IceSpirit.webp' },
  { name: 'Ice Wizard', image: '/assets/clash-royale/cards/IceWiz.webp' },
  { name: 'Inferno Tower', image: '/assets/clash-royale/cards/Inferno.webp' },
  { name: 'Inferno Dragon', image: '/assets/clash-royale/cards/InfernoD.webp' },
  { name: 'Knight', image: '/assets/clash-royale/cards/Knight.webp' },
  { name: 'Lava Hound', image: '/assets/clash-royale/cards/Lava.webp' },
  { name: 'Lightning', image: '/assets/clash-royale/cards/Lightning.webp' },
  { name: 'Little Prince', image: '/assets/clash-royale/cards/LittlePrince.webp' },
  { name: 'The Log', image: '/assets/clash-royale/cards/Log.webp' },
  { name: 'Lumberjack', image: '/assets/clash-royale/cards/Lumber.webp' },
  { name: 'Magic Archer', image: '/assets/clash-royale/cards/MagicArcher.webp' },
  { name: 'Mega Knight', image: '/assets/clash-royale/cards/MegaKnight.webp' },
  { name: 'Mighty Miner', image: '/assets/clash-royale/cards/MightyMiner.webp' },
  { name: 'Miner', image: '/assets/clash-royale/cards/Miner.webp' },
  { name: 'Minions', image: '/assets/clash-royale/cards/Minions.webp' },
  { name: 'Mini P.E.K.K.A.', image: '/assets/clash-royale/cards/MiniPekka.webp' },
  { name: 'Mirror', image: '/assets/clash-royale/cards/Mirror.webp' },
  { name: 'Mega Minion', image: '/assets/clash-royale/cards/MM.webp' },
  { name: 'Monk', image: '/assets/clash-royale/cards/Monk.webp' },
  { name: 'Mortar', image: '/assets/clash-royale/cards/Mortar.webp' },
  { name: 'Mother Witch', image: '/assets/clash-royale/cards/MotherWitch.webp' },
  { name: 'Musketeer', image: '/assets/clash-royale/cards/Musk.webp' },
  { name: 'Night Witch', image: '/assets/clash-royale/cards/NightWitch.webp' },
  { name: 'P.E.K.K.A.', image: '/assets/clash-royale/cards/PEKKA.webp' },
  { name: 'Phoenix', image: '/assets/clash-royale/cards/Phoenix.webp' },
  { name: 'Poison', image: '/assets/clash-royale/cards/Poison.webp' },
  { name: 'Prince', image: '/assets/clash-royale/cards/Prince.webp' },
  { name: 'Princess', image: '/assets/clash-royale/cards/Princess.webp' },
  { name: 'Elixir Collector', image: '/assets/clash-royale/cards/Pump.webp' },
  { name: 'Rage', image: '/assets/clash-royale/cards/Rage.webp' },
  { name: 'Battle Ram', image: '/assets/clash-royale/cards/Ram.webp' },
  { name: 'Ram Rider', image: '/assets/clash-royale/cards/RamRider.webp' },
  { name: 'Rascals', image: '/assets/clash-royale/cards/Rascals.webp' },
  { name: 'Royal Giant', image: '/assets/clash-royale/cards/RG.webp' },
  { name: 'Rocket', image: '/assets/clash-royale/cards/Rocket.webp' },
  { name: 'Royal Delivery', image: '/assets/clash-royale/cards/RoyalDelivery.webp' },
  { name: 'Royal Hogs', image: '/assets/clash-royale/cards/RoyalHogs.webp' },
  { name: 'Royal Recruits', image: '/assets/clash-royale/cards/RoyalRecruits.webp' },
  { name: 'Rune Giant', image: '/assets/clash-royale/cards/RuneGiant.webp' },
  { name: 'Skeleton Army', image: '/assets/clash-royale/cards/Skarmy.webp' },
  { name: 'Skeleton Dragons', image: '/assets/clash-royale/cards/SkeletonDragons.webp' },
  { name: 'Skeleton King', image: '/assets/clash-royale/cards/SkeletonKing.webp' },
  { name: 'Skeletons', image: '/assets/clash-royale/cards/Skellies.webp' },
  { name: 'Skeleton Barrel', image: '/assets/clash-royale/cards/SkellyBarrel.webp' },
  { name: 'Giant Snowball', image: '/assets/clash-royale/cards/Snowball.webp' },
  { name: 'Sparky', image: '/assets/clash-royale/cards/Sparky.webp' },
  { name: 'Spear Goblins', image: '/assets/clash-royale/cards/SpearGobs.webp' },
  { name: 'Spirit Empress', image: '/assets/clash-royale/cards/SpiritEmpress.webp' },
  { name: 'Suspicious Bush', image: '/assets/clash-royale/cards/SuspiciousBush.webp' },
  { name: 'Tesla', image: '/assets/clash-royale/cards/Tesla.webp' },
  { name: 'Tombstone', image: '/assets/clash-royale/cards/Tombstone.webp' },
  { name: 'Tornado', image: '/assets/clash-royale/cards/Tornado.webp' },
  { name: 'Valkyrie', image: '/assets/clash-royale/cards/Valk.webp' },
  { name: 'Vines', image: '/assets/clash-royale/cards/Vines.webp' },
  { name: 'Void', image: '/assets/clash-royale/cards/Void.webp' },
  { name: 'Wall Breakers', image: '/assets/clash-royale/cards/WallBreakers.webp' },
  { name: 'Witch', image: '/assets/clash-royale/cards/Witch.webp' },
  { name: 'Wizard', image: '/assets/clash-royale/cards/Wiz.webp' },
  { name: 'X-Bow', image: '/assets/clash-royale/cards/XBow.webp' },
  { name: 'Zap', image: '/assets/clash-royale/cards/Zap.webp' },
  { name: 'Zappies', image: '/assets/clash-royale/cards/Zappies.webp' },
];

function randomFrom(list) {
  if (!list?.length) return null;
  return list[Math.floor(Math.random() * list.length)];
}

export function pickCard() {
  return randomFrom(cards);
}
