'use client';

const wordDatabase = [
  {
    id: 'everyday',
    name: 'Objects and Things',
    entries: [
      // Easy — Kitchen Items
      { difficulty: 'easy', word: 'Mug', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Coaster', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Apron', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Mixing Bowl', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Cutting Board', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Spice Rack', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Tray', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Peeler', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Oven Mitt', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Tongs', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Spatula', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Toaster', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Refrigerator', hint: 'Kitchen Items' },
      { difficulty: 'easy', word: 'Stove', hint: 'Kitchen Items' },

      // Easy — Office and School Supplies
      { difficulty: 'easy', word: 'Folder', hint: 'Office And School Supplies' },
      { difficulty: 'easy', word: 'Notebook', hint: 'Office And School Supplies' },
      { difficulty: 'easy', word: 'Sticky Notes', hint: 'Office And School Supplies' },
      { difficulty: 'easy', word: 'Paper Clips', hint: 'Office And School Supplies' },
      { difficulty: 'easy', word: 'Tape', hint: 'Office And School Supplies' },
      { difficulty: 'easy', word: 'Marker', hint: 'Office And School Supplies' },
      { difficulty: 'easy', word: 'Stapler', hint: 'Office And School Supplies' },

      // Easy - Accessories
      { difficulty: 'easy', word: 'Wallet', hint: 'Accessories' },
      { difficulty: 'easy', word: 'Backpack', hint: 'Accessories' },
      { difficulty: 'easy', word: 'Sunglasses', hint: 'Accessories' },
      { difficulty: 'easy', word: 'Bracelet', hint: 'Accessories' },
      { difficulty: 'easy', word: 'Belt', hint: 'Accessories' },
      { difficulty: 'easy', word: 'Keychain', hint: 'Accessories' },
      { difficulty: 'easy', word: 'Gloves', hint: 'Accessories' },

      // Easy - Outdoor Items
      { difficulty: 'easy', word: 'Umbrella', hint: 'Outdoor Items' },
      { difficulty: 'easy', word: 'Raincoat', hint: 'Outdoor Items' },
      { difficulty: 'easy', word: 'Campfire', hint: 'Outdoor Items' },
      { difficulty: 'easy', word: 'Bug Spray', hint: 'Outdoor Items' },
      { difficulty: 'easy', word: 'Bicycle', hint: 'Outdoor Items' },
      { difficulty: 'easy', word: 'Picnic Basket', hint: 'Outdoor Items' },

      // Easy - Plants
      { difficulty: 'easy', word: 'Sunflower', hint: 'Plants' },
      { difficulty: 'easy', word: 'Maple Tree', hint: 'Plants' },
      { difficulty: 'easy', word: 'Bamboo Shoot', hint: 'Plants' },

      // Easy - Bedroom Items
      { difficulty: 'easy', word: 'Blanket', hint: 'Bedroom Items' },
      { difficulty: 'easy', word: 'Pillow', hint: 'Bedroom Items' },
      { difficulty: 'easy', word: 'Curtain', hint: 'Bedroom Items' },

      // Easy - Tools and Equipment
      { difficulty: 'easy', word: 'Flashlight', hint: 'Tools And Equipment' },
      { difficulty: 'easy', word: 'Scissors', hint: 'Tools And Equipment' },
      { difficulty: 'easy', word: 'Tape Measure', hint: 'Tools And Equipment' },
      { difficulty: 'easy', word: 'Hard Hat', hint: 'Tools And Equipment' },
      { difficulty: 'easy', word: 'Hammer', hint: 'Tools And Equipment' },

      // Easy - Objects and Things
      { difficulty: 'easy', word: 'Toothbrush', hint: 'Objects And Things' },
      { difficulty: 'easy', word: 'Trash Can', hint: 'Objects And Things' },
      { difficulty: 'easy', word: 'Candle', hint: 'Objects And Things' },
      { difficulty: 'easy', word: 'Picture Frame', hint: 'Objects And Things' },
      { difficulty: 'easy', word: 'Bookmark', hint: 'Objects And Things' },
      { difficulty: 'easy', word: 'Wind Chime', hint: 'Objects And Things' },
      { difficulty: 'easy', word: 'Paperweight', hint: 'Objects And Things' },
      { difficulty: 'easy', word: 'Remote Control', hint: 'Objects And Things' },

      // Medium - Kitchen Items
      { difficulty: 'medium', word: 'Microwave', hint: 'Kitchen Items' },
      { difficulty: 'medium', word: 'Measuring Cup', hint: 'Kitchen Items' },
      { difficulty: 'medium', word: 'Electric Kettle', hint: 'Kitchen Items' },
      { difficulty: 'medium', word: 'Blender', hint: 'Kitchen Items' },
      { difficulty: 'medium', word: 'Air Fryer', hint: 'Kitchen Items' },
      { difficulty: 'medium', word: 'Skillet', hint: 'Kitchen Items' },
      { difficulty: 'medium', word: 'Teapot', hint: 'Kitchen Items' },
      { difficulty: 'medium', word: 'Juicer', hint: 'Kitchen Items' },

      // Medium - Office and School Supplies
      { difficulty: 'medium', word: 'Calendar', hint: 'Office And School Supplies' },
      { difficulty: 'medium', word: 'Whiteboard', hint: 'Office And School Supplies' },
      { difficulty: 'medium', word: 'Projector', hint: 'Office And School Supplies' },
      { difficulty: 'medium', word: 'Standing Desk', hint: 'Office And School Supplies' },
      { difficulty: 'medium', word: 'File Cabinet', hint: 'Office And School Supplies' },
      { difficulty: 'medium', word: 'Shredder', hint: 'Office And School Supplies' },

      // Medium - Accessories
      { difficulty: 'medium', word: 'Lanyard', hint: 'Accessories' },
      { difficulty: 'medium', word: 'Neck Pillow', hint: 'Accessories' },
      { difficulty: 'medium', word: 'Pocket Square', hint: 'Accessories' },
      { difficulty: 'medium', word: 'Money Clip', hint: 'Accessories' },

      // Medium — Outdoor Items
      { difficulty: 'medium', word: 'Hammock', hint: 'Outdoor Items' },
      { difficulty: 'medium', word: 'Kayak', hint: 'Outdoor Items' },
      { difficulty: 'medium', word: 'Headlamp', hint: 'Outdoor Items' },
      { difficulty: 'medium', word: 'Canteen', hint: 'Outdoor Items' },
      { difficulty: 'medium', word: 'Hiking Boots', hint: 'Outdoor Items' },

      // Medium - Tools and Equipment
      { difficulty: 'medium', word: 'Thermostat', hint: 'Tools And Equipment' },
      { difficulty: 'medium', word: 'Vacuum Cleaner', hint: 'Tools And Equipment' },
      { difficulty: 'medium', word: 'Air Purifier', hint: 'Tools And Equipment' },
      { difficulty: 'medium', word: 'Pulley', hint: 'Tools And Equipment' },

      // Medium - Objects and Things
      { difficulty: 'medium', word: 'Bookshelf', hint: 'Objects And Things' },
      { difficulty: 'medium', word: 'Clock', hint: 'Objects And Things' },
      { difficulty: 'medium', word: 'Globe', hint: 'Objects And Things' },
      { difficulty: 'medium', word: 'Mirror', hint: 'Objects And Things' },

      // Hard - Accessories
      { difficulty: 'hard', word: 'Shoe Horn', hint: 'Accessories' },

      // Hard - Outdoor Items
      { difficulty: 'hard', word: 'Snowshoes', hint: 'Outdoor Items' },
      { difficulty: 'hard', word: 'Axe', hint: 'Outdoor Items' },
      { difficulty: 'hard', word: 'Beacon', hint: 'Outdoor Items' },
      { difficulty: 'hard', word: 'Climbing Harness', hint: 'Outdoor Items' },
      { difficulty: 'hard', word: 'Tent', hint: 'Outdoor Items' },
      { difficulty: 'hard', word: 'Crampons', hint: 'Outdoor Items' },

      // Hard - Kitchen Items
      { difficulty: 'hard', word: 'Pressure Cooker', hint: 'Kitchen Items' },
      { difficulty: 'hard', word: 'Espresso Machine', hint: 'Kitchen Items' },
      { difficulty: 'hard', word: 'Smoker', hint: 'Kitchen Items' },
      { difficulty: 'hard', word: 'Ice Cream Maker', hint: 'Kitchen Items' },
      { difficulty: 'hard', word: 'Meat Grinder', hint: 'Kitchen Items' },
      { difficulty: 'hard', word: 'Mortar And Pestle', hint: 'Kitchen Items' },

      // Hard - Tools and Equipment
      { difficulty: 'hard', word: '3D Printer', hint: 'Tools And Equipment' },
      { difficulty: 'hard', word: 'Anvil', hint: 'Tools And Equipment' },
      { difficulty: 'hard', word: 'Laser Cutter', hint: 'Tools And Equipment' },
      { difficulty: 'hard', word: 'Blowtorch', hint: 'Tools And Equipment' },
      { difficulty: 'hard', word: 'Vacuum Sealer', hint: 'Tools And Equipment' },
    ]
      },
  {
    id: 'food',
    name: 'Food',
    entries: [
      { difficulty: 'easy', word: 'Pizza' },
      { difficulty: 'easy', word: 'Pancake' },
      { difficulty: 'easy', word: 'Burger' },
      { difficulty: 'easy', word: 'Cheeseburger' },
      { difficulty: 'easy', word: 'Salad' },
      { difficulty: 'easy', word: 'Taco' },
      { difficulty: 'easy', word: 'Cookie' },
      { difficulty: 'easy', word: 'Coffee' },
      { difficulty: 'easy', word: 'Tea' },
      { difficulty: 'easy', word: 'Sandwich' },
      { difficulty: 'easy', word: 'Apple' },
      { difficulty: 'easy', word: 'Trail Mix' },
      { difficulty: 'easy', word: 'Smoothie' },
      { difficulty: 'easy', word: 'Fries' },
      { difficulty: 'easy', word: 'Donut' },
      { difficulty: 'easy', word: 'Brownie' },
      { difficulty: 'easy', word: 'Waffle' },
      { difficulty: 'easy', word: 'Popcorn' },
      { difficulty: 'easy', word: 'Muffin' },
      { difficulty: 'easy', word: 'Pretzel' },
      { difficulty: 'easy', word: 'Burrito' },
      { difficulty: 'easy', word: 'Milkshake' },
      { difficulty: 'easy', word: 'Nachos' },
      { difficulty: 'easy', word: 'Marshmallow' },
      { difficulty: 'easy', word: 'Gummy Bear' },
      { difficulty: 'easy', word: 'Honey' },
      { difficulty: 'easy', word: 'Ketchup' },
      { difficulty: 'easy', word: 'Salt' },
      { difficulty: 'easy', word: 'Cheese' },
      { difficulty: 'easy', word: 'Butter' },
      { difficulty: 'easy', word: 'Banana' },
      { difficulty: 'easy', word: 'Orange' },
      { difficulty: 'easy', word: 'Grape' },
      { difficulty: 'easy', word: 'Strawberry' },
      { difficulty: 'easy', word: 'Blueberry' },
      { difficulty: 'easy', word: 'Raspberry' },
      { difficulty: 'easy', word: 'Blackberry' },
      { difficulty: 'easy', word: 'Peach' },
      { difficulty: 'easy', word: 'Pear' },
      { difficulty: 'easy', word: 'Plum' },
      { difficulty: 'easy', word: 'Cherry' },
      { difficulty: 'easy', word: 'Watermelon' },
      { difficulty: 'easy', word: 'Melon' },
      { difficulty: 'easy', word: 'Pineapple' },
      { difficulty: 'easy', word: 'Mango' },
      { difficulty: 'easy', word: 'Kiwi' },
      { difficulty: 'easy', word: 'Lemon' },
      { difficulty: 'easy', word: 'Coconut' },
      { difficulty: 'easy', word: 'Avocado' },
      { difficulty: 'easy', word: 'Tomato' },
      { difficulty: 'easy', word: 'Cucumber' },
      { difficulty: 'easy', word: 'Carrot' },
      { difficulty: 'easy', word: 'Potato' },
      { difficulty: 'easy', word: 'Onion' },
      { difficulty: 'easy', word: 'Garlic' },
      { difficulty: 'easy', word: 'Lettuce' },
      { difficulty: 'easy', word: 'Broccoli' },
      { difficulty: 'easy', word: 'Cauliflower' },
      { difficulty: 'easy', word: 'Pumpkin' },
      { difficulty: 'easy', word: 'Grilled Cheese' },
      { difficulty: 'easy', word: 'Chicken Nuggets' },
      { difficulty: 'easy', word: 'Hot Dog' },
      { difficulty: 'easy', word: 'Ice Cream' },
      { difficulty: 'easy', word: 'Bacon' },
      { difficulty: 'easy', word: 'Chicken' },
      { difficulty: 'easy', word: 'Steak' },
      { difficulty: 'easy', word: 'Fish' },
      { difficulty: 'easy', word: 'Shrimp' },
      { difficulty: 'easy', word: 'Yogurt' },
      { difficulty: 'easy', word: 'Meatballs' },
      { difficulty: 'easy', word: 'Apple Pie' },
      { difficulty: 'medium', word: 'Spring Rolls' },
      { difficulty: 'medium', word: 'Dumpling' },
      { difficulty: 'medium', word: 'Lasagna' },
      { difficulty: 'medium', word: 'Sushi Roll' },
      { difficulty: 'medium', word: 'Cupcake' },
      { difficulty: 'medium', word: 'Curry' },
      { difficulty: 'medium', word: 'Omelette' },
      { difficulty: 'medium', word: 'Stew' },
      { difficulty: 'medium', word: 'Ramen' },
      { difficulty: 'medium', word: 'Shawarma' },
      { difficulty: 'medium', word: 'Kimchi' },
      { difficulty: 'medium', word: 'Pad Thai' },
      { difficulty: 'medium', word: 'Baklava' },
      { difficulty: 'medium', word: 'Butter Chicken' },
      { difficulty: 'medium', word: 'Lobster' },
      { difficulty: 'medium', word: 'Mushrooms' },
      { difficulty: 'medium', word: 'Juice' },
      { difficulty: 'medium', word: 'Milk' },
      { difficulty: 'medium', word: 'Lemonade' },
      { difficulty: 'medium', word: 'Wings' },
      { difficulty: 'hard', word: 'Souffle' },
      { difficulty: 'hard', word: 'Ratatouille' },
      { difficulty: 'hard', word: 'Tiramisu' },
      { difficulty: 'hard', word: 'Charcuterie Board' },
      { difficulty: 'hard', word: 'Popsicle' },
      { difficulty: 'hard', word: 'Beef Wellington' },
      { difficulty: 'hard', word: 'Pierogi' },
      { difficulty: 'hard', word: 'Crème Brûlée' },
      { difficulty: 'hard', word: 'Borscht' },
      { difficulty: 'hard', word: 'Guacamole' },
    ]
      },
  {
    id: 'history',
    name: 'History',
    entries: [
      { difficulty: 'easy', word: 'Moon Landing' },
      { difficulty: 'easy', word: 'Gutenberg Bible' },
      { difficulty: 'easy', word: 'Fall of the Berlin Wall' },
      { difficulty: 'easy', word: 'World War One' },
      { difficulty: 'easy', word: 'World War Two' },
      { difficulty: 'easy', word: 'American Revolution' },
      { difficulty: 'easy', word: 'French Revolution' },
      { difficulty: 'easy', word: 'Discovery of America' },
      { difficulty: 'easy', word: 'Signing of the Declaration of Independence' },
      { difficulty: 'easy', word: 'Boston Tea Party' },
      { difficulty: 'easy', word: 'Pearl Harbor' },
      { difficulty: 'easy', word: 'D-Day' },
      { difficulty: 'easy', word: 'Cold War' },
      { difficulty: 'easy', word: 'Great Depression' },
      { difficulty: 'easy', word: 'Russian Revolution' },
      { difficulty: 'easy', word: 'Assassination of JFK' },
      { difficulty: 'easy', word: 'Cuban Missile Crisis' },
      { difficulty: 'easy', word: 'Vietnam War' },
      { difficulty: 'easy', word: 'Napoleonic Wars' },
      { difficulty: 'easy', word: 'Irish Potato Famine' },
      { difficulty: 'easy', word: 'Fall of the Soviet Union' },
      { difficulty: 'easy', word: 'Coronation of Queen Elizabeth II' },
      { difficulty: 'easy', word: 'Chernobyl Disaster' },
      { difficulty: 'easy', word: 'Launch of Sputnik' },
      { difficulty: 'easy', word: 'First Flight of the Wright Brothers' },
      { difficulty: 'easy', word: 'Painting of the Mona Lisa' },
      { difficulty: 'easy', word: 'Building of the Sistine Chapel' },
      { difficulty: 'easy', word: 'Printing Press Invented' },
      { difficulty: 'easy', word: 'Birth of Jesus Christ' },
      { difficulty: 'easy', word: 'Assassination of Julius Caesar' },
      { difficulty: 'easy', word: 'Hitler Invades Poland' },
      { difficulty: 'easy', word: 'Assassination of Abraham Lincoln' },
      { difficulty: 'easy', word: 'Bombing of Hiroshima and Nagasaki' },
      { difficulty: 'easy', word: 'Creation of Israel' },
      { difficulty: 'easy', word: 'Discovery of Penicillin' },
      { difficulty: 'easy', word: 'First Man in Space' },
      { difficulty: 'easy', word: 'Titanic Sinks' },
      { difficulty: 'easy', word: 'Great Fire of London' },
      { difficulty: 'easy', word: 'Pompeii Buried by Volcano' },
      { difficulty: 'medium', word: 'Battle of Waterloo' },
      { difficulty: 'medium', word: 'Battle of Gettysburg' },
      { difficulty: 'medium', word: 'Treaty of Versailles' },
      { difficulty: 'medium', word: 'Signing of the Magna Carta' },
      { difficulty: 'medium', word: 'Spanish Inquisition' },
      { difficulty: 'medium', word: 'Black Death' },
      { difficulty: 'medium', word: 'Fall of the Roman Empire' },
      { difficulty: 'medium', word: 'War of 1812' },
      { difficulty: 'medium', word: 'California Gold Rush' },
      { difficulty: 'medium', word: 'Opium Wars' },
      { difficulty: 'medium', word: 'Boxer Rebellion' },
      { difficulty: 'medium', word: 'Fall of Constantinople' },
      { difficulty: 'medium', word: 'Yalta Conference' },
      { difficulty: 'medium', word: 'Congress of Vienna' },
      { difficulty: 'medium', word: 'Fall of Yugoslavia' },
      { difficulty: 'medium', word: 'Assassination of Archduke Franz Ferdinand' },
      { difficulty: 'medium', word: 'Berlin Airlift' },
      { difficulty: 'medium', word: 'Founding of NATO' },
      { difficulty: 'medium', word: 'Coronation of Charlemagne' },
      { difficulty: 'medium', word: 'Battle of Midway' },
      { difficulty: 'medium', word: 'Siege of Sarajevo' },
      { difficulty: 'medium', word: 'The Crusades' },
      { difficulty: 'medium', word: 'Gallipoli Campaign' },
      { difficulty: 'medium', word: 'Operation Barbarossa' },
      { difficulty: 'medium', word: 'Protestant Reformation' },
      { difficulty: 'medium', word: "Henry VIII's Six Wives" },
      { difficulty: 'medium', word: 'Joan of Arc Killed' },
      { difficulty: 'medium', word: 'Creation of the Papal States' },
      { difficulty: 'medium', word: 'Constantine Converts to Christianity' },
      { difficulty: 'medium', word: 'Otto von Bismarck Unifies Germany' },
      { difficulty: 'medium', word: 'William the Conqueror Invades England' },
      { difficulty: 'medium', word: 'Socrates Sentenced to Death' },
      { difficulty: 'medium', word: 'The Final Solution' },
      { difficulty: 'medium', word: 'Manhattan Project' },
      { difficulty: 'medium', word: 'London Blitz' },
      { difficulty: 'medium', word: 'Chicago Fire' },
      { difficulty: 'medium', word: 'Watergate Scandal' },
      { difficulty: 'medium', word: 'San Francisco Earthquake' },
      { difficulty: 'medium', word: 'Bay of Pigs' },
      { difficulty: 'medium', word: 'Space Race' },
      { difficulty: 'medium', word: 'Arab Spring' },
      { difficulty: 'medium', word: 'Falklands War' },
      { difficulty: 'medium', word: 'Nuremberg Trials' },
      { difficulty: 'hard', word: 'Thirty Years War' },
      { difficulty: 'hard', word: 'Seven Years War' },
      { difficulty: 'hard', word: 'Hundred Years War' },
      { difficulty: 'hard', word: 'Battle of Stalingrad' },
      { difficulty: 'hard', word: 'Battle of Thermopylae' },
      { difficulty: 'hard', word: 'Peloponnesian War' },
      { difficulty: 'hard', word: 'Boer War' },
      { difficulty: 'hard', word: "Caesar's Civil War" },
      { difficulty: 'hard', word: 'Rubicon Crossing' },
      { difficulty: 'hard', word: 'Siege of Vienna' },
      { difficulty: 'hard', word: 'Night of the Long Knives' },
      { difficulty: 'hard', word: 'Great Schism of 1054' },
      { difficulty: 'hard', word: 'Chinese Cultural Revolution' },
      { difficulty: 'hard', word: "Genghis Khan's Conquests" },
      { difficulty: 'hard', word: "Alexander the Great's Conquests" },
      { difficulty: 'hard', word: 'Hannibal Crosses the Alps' },
      { difficulty: 'hard', word: 'Spartacus Leads a Slave Revolt' },
      { difficulty: 'hard', word: 'The Life of Cleopatra' },
      { difficulty: 'medium', word: 'American Prohibition' },
      { difficulty: 'hard', word: 'The Reconquista' },
    ]
      },
  {
    id: 'countriesCities',
    name: 'Countries and Cities',
    entries: [
      { difficulty: 'easy', word: 'France' },
      { difficulty: 'easy', word: 'Germany' },
      { difficulty: 'easy', word: 'Italy' },
      { difficulty: 'easy', word: 'Spain' },
      { difficulty: 'easy', word: 'United Kingdom' },
      { difficulty: 'easy', word: 'Ireland' },
      { difficulty: 'easy', word: 'Portugal' },
      { difficulty: 'easy', word: 'Belgium' },
      { difficulty: 'easy', word: 'Switzerland' },
      { difficulty: 'easy', word: 'Sweden' },
      { difficulty: 'easy', word: 'Finland' },
      { difficulty: 'easy', word: 'Greece' },
      { difficulty: 'easy', word: 'Poland' },
      { difficulty: 'easy', word: 'Ukraine' },
      { difficulty: 'easy', word: 'United States' },
      { difficulty: 'easy', word: 'Canada' },
      { difficulty: 'easy', word: 'Mexico' },
      { difficulty: 'easy', word: 'Brazil' },
      { difficulty: 'easy', word: 'Argentina' },
      { difficulty: 'easy', word: 'South Africa' },
      { difficulty: 'easy', word: 'China' },
      { difficulty: 'easy', word: 'Japan' },
      { difficulty: 'easy', word: 'South Korea' },
      { difficulty: 'easy', word: 'North Korea' },
      { difficulty: 'easy', word: 'India' },
      { difficulty: 'easy', word: 'Australia' },
      { difficulty: 'easy', word: 'New Zealand' },
      { difficulty: 'medium', word: 'Hungary' },
      { difficulty: 'medium', word: 'Bulgaria' },
      { difficulty: 'medium', word: 'Croatia' },
      { difficulty: 'medium', word: 'Serbia' },
      { difficulty: 'medium', word: 'Albania' },
      { difficulty: 'medium', word: 'Belarus' },
      { difficulty: 'medium', word: 'Iceland' },
      { difficulty: 'medium', word: 'Cyprus' },
      { difficulty: 'medium', word: 'Russia' },
      { difficulty: 'medium', word: 'Turkey' },
      { difficulty: 'medium', word: 'Taiwan' },
      { difficulty: 'medium', word: 'Israel' },
      { difficulty: 'medium', word: 'Saudi Arabia' },
      { difficulty: 'medium', word: 'Iran' },
      { difficulty: 'medium', word: 'Iraq' },
      { difficulty: 'medium', word: 'Syria' },
      { difficulty: 'medium', word: 'United Arab Emirates' },
      { difficulty: 'medium', word: 'Qatar' },
      { difficulty: 'medium', word: 'Afghanistan' },
      { difficulty: 'medium', word: 'Indonesia' },
      { difficulty: 'medium', word: 'Vietnam' },
      { difficulty: 'medium', word: 'Thailand' },
      { difficulty: 'medium', word: 'Philippines' },
      { difficulty: 'medium', word: 'Singapore' },
      { difficulty: 'medium', word: 'Kazakhstan' },
      { difficulty: 'medium', word: 'Egypt' },
      { difficulty: 'medium', word: 'Pakistan' },
      { difficulty: 'medium', word: 'Bangladesh' },
      { difficulty: 'medium', word: 'Malaysia' },
      { difficulty: 'medium', word: 'Colombia' },
      { difficulty: 'medium', word: 'Chile' },
      { difficulty: 'medium', word: 'Peru' },
      { difficulty: 'hard', word: 'Luxembourg' },
      { difficulty: 'hard', word: 'Malta' },
      { difficulty: 'hard', word: 'Andorra' },
      { difficulty: 'hard', word: 'Monaco' },
      { difficulty: 'hard', word: 'Liechtenstein' },
      { difficulty: 'hard', word: 'Vatican City' },
      { difficulty: 'hard', word: 'Georgia' },
      { difficulty: 'hard', word: 'Armenia' },
      { difficulty: 'hard', word: 'Azerbaijan' },
      { difficulty: 'hard', word: 'Moldova' },
      { difficulty: 'hard', word: 'Bosnia and Herzegovina' },
      { difficulty: 'hard', word: 'North Macedonia' },
      { difficulty: 'hard', word: 'Montenegro' },
      { difficulty: 'hard', word: 'Kosovo' },
      { difficulty: 'hard', word: 'Slovenia' },
      { difficulty: 'hard', word: 'Slovakia' },
      { difficulty: 'hard', word: 'Czechia' },
      { difficulty: 'hard', word: 'Estonia' },
      { difficulty: 'hard', word: 'Latvia' },
      { difficulty: 'hard', word: 'Lithuania' },
      { difficulty: 'medium', word: 'Kuwait' },
      { difficulty: 'medium', word: 'Oman' },
      { difficulty: 'medium', word: 'Jordan' },
    ]
      },
  {
    id: 'abstract',
    name: 'Abstract and Miscelaneous',
    entries: [
      { difficulty: 'easy', word: 'Love', hint: 'Heart' },
      { difficulty: 'easy', word: 'Fear', hint: 'Terror' },
      { difficulty: 'easy', word: 'Hope', hint: 'Future' },
      { difficulty: 'easy', word: 'Faith', hint: 'Belief' },
      { difficulty: 'easy', word: 'Chaos', hint: 'Mess' },
      { difficulty: 'easy', word: 'Peace', hint: 'Calm' },
      { difficulty: 'easy', word: 'Trust', hint: 'Reliance' },
      { difficulty: 'easy', word: 'Pride', hint: 'Honor' },
      { difficulty: 'easy', word: 'Shame', hint: 'Guilt' },
      { difficulty: 'easy', word: 'Joy', hint: 'Happiness' },
      { difficulty: 'easy', word: 'Anger', hint: 'Rage' },
      { difficulty: 'easy', word: 'Kindness', hint: 'Care' },
      { difficulty: 'easy', word: 'Greed', hint: 'Wanting' },
      { difficulty: 'easy', word: 'Envy', hint: 'Jealousy' },
      { difficulty: 'easy', word: 'Hate', hint: 'Loathing' },
      { difficulty: 'easy', word: 'Friendship', hint: 'Bond' },
      { difficulty: 'easy', word: 'Loneliness', hint: 'Alone' },
      { difficulty: 'easy', word: 'Patience', hint: 'Waiting' },
      { difficulty: 'easy', word: 'Honesty', hint: 'Truth' },
      { difficulty: 'easy', word: 'Loyalty', hint: 'Faithful' },
      { difficulty: 'easy', word: 'Respect', hint: 'Honor' },
      { difficulty: 'easy', word: 'Curiosity', hint: 'Wonder' },
      { difficulty: 'easy', word: 'Creativity', hint: 'Imagination' },
      { difficulty: 'easy', word: 'Motivation', hint: 'Drive' },
      { difficulty: 'easy', word: 'Stress', hint: 'Pressure' },
      { difficulty: 'easy', word: 'Luck', hint: 'Fortune' },
      { difficulty: 'easy', word: 'Calmness', hint: 'Still' },
      { difficulty: 'easy', word: 'Excitement', hint: 'Thrill' },
      { difficulty: 'easy', word: 'Surprise', hint: 'Shock' },
      { difficulty: 'easy', word: 'Gratitude', hint: 'Thanks' },
      { difficulty: 'easy', word: 'Guilt', hint: 'Regret' },
      { difficulty: 'easy', word: 'Comfort', hint: 'Ease' },
      { difficulty: 'easy', word: 'Doubt', hint: 'Uncertainty' },
      { difficulty: 'easy', word: 'Relief', hint: 'Release' },
      { difficulty: 'easy', word: 'Boredom', hint: 'Dull' },
      { difficulty: 'easy', word: 'Confidence', hint: 'Assurance' },
      { difficulty: 'easy', word: 'Inspiration', hint: 'Idea' },
      { difficulty: 'easy', word: 'Temptation', hint: 'Urge' },
      { difficulty: 'easy', word: 'Satisfaction', hint: 'Content' },
      { difficulty: 'medium', word: 'Identity', hint: 'Self' },
      { difficulty: 'medium', word: 'Freedom', hint: 'Liberty' },
      { difficulty: 'medium', word: 'Courage', hint: 'Bravery' },
      { difficulty: 'medium', word: 'Wisdom', hint: 'Insight' },
      { difficulty: 'medium', word: 'Destiny', hint: 'Fate' },
      { difficulty: 'medium', word: 'Illusion', hint: 'Trick' },
      { difficulty: 'medium', word: 'Balance', hint: 'Stability' },
      { difficulty: 'medium', word: 'Desire', hint: 'Want' },
      { difficulty: 'medium', word: 'Morality', hint: 'Ethics' },
      { difficulty: 'medium', word: 'Empathy', hint: 'Understanding' },
      { difficulty: 'medium', word: 'Compassion', hint: 'Mercy' },
      { difficulty: 'medium', word: 'Resilience', hint: 'Recovery' },
      { difficulty: 'medium', word: 'Integrity', hint: 'Principles' },
      { difficulty: 'medium', word: 'Ambition', hint: 'Goal' },
      { difficulty: 'medium', word: 'Intuition', hint: 'Instinct' },
      { difficulty: 'medium', word: 'Perception', hint: 'Awareness' },
      { difficulty: 'medium', word: 'Influence', hint: 'Impact' },
      { difficulty: 'medium', word: 'Reputation', hint: 'Status' },
      { difficulty: 'medium', word: 'Legacy', hint: 'Memory' },
      { difficulty: 'medium', word: 'Tradition', hint: 'Custom' },
      { difficulty: 'medium', word: 'Innovation', hint: 'Newness' },
      { difficulty: 'medium', word: 'Progress', hint: 'Advance' },
      { difficulty: 'medium', word: 'Conflict', hint: 'Clash' },
      { difficulty: 'medium', word: 'Harmony', hint: 'Unity' },
      { difficulty: 'medium', word: 'Authority', hint: 'Power' },
      { difficulty: 'medium', word: 'Obedience', hint: 'Compliance' },
      { difficulty: 'medium', word: 'Rebellion', hint: 'Revolt' },
      { difficulty: 'medium', word: 'Isolation', hint: 'Separation' },
      { difficulty: 'medium', word: 'Connection', hint: 'Link' },
      { difficulty: 'medium', word: 'Mindfulness', hint: 'Presence' },
      { difficulty: 'medium', word: 'Authenticity', hint: 'Genuine' },
      { difficulty: 'medium', word: 'Vulnerability', hint: 'Exposure' },
      { difficulty: 'medium', word: 'Accountability', hint: 'Responsibility' },
      { difficulty: 'medium', word: 'Adaptability', hint: 'Flexibility' },
      { difficulty: 'medium', word: 'Dependence', hint: 'Reliance' },
      { difficulty: 'medium', word: 'Interdependence', hint: 'Mutual' },
      { difficulty: 'medium', word: 'Mindset', hint: 'Attitude' },
      { difficulty: 'medium', word: 'Fulfillment', hint: 'Completion' },
      { difficulty: 'medium', word: 'Contentment', hint: 'Satisfaction' },
      { difficulty: 'hard', word: 'Consciousness', hint: 'Awareness' },
      { difficulty: 'hard', word: 'Determinism', hint: 'Causality' },
      { difficulty: 'hard', word: 'Existentialism', hint: 'Meaning' },
      { difficulty: 'hard', word: 'Duality', hint: 'Opposites' },
      { difficulty: 'hard', word: 'Subjectivity', hint: 'Perspective' },
      { difficulty: 'hard', word: 'Nihilism', hint: 'Nothingness' },
      { difficulty: 'hard', word: 'Transcendence', hint: 'Beyond' },
      { difficulty: 'hard', word: 'Equilibrium', hint: 'Balance' },
      { difficulty: 'hard', word: 'Altruism', hint: 'Selflessness' },
      { difficulty: 'hard', word: 'Utilitarianism', hint: 'Outcome' },
      { difficulty: 'hard', word: 'Epistemology', hint: 'Knowledge' },
      { difficulty: 'hard', word: 'Ontology', hint: 'Being' },
      { difficulty: 'hard', word: 'Dialectic', hint: 'Debate' },
      { difficulty: 'hard', word: 'Phenomenology', hint: 'Experience' },
      { difficulty: 'hard', word: 'Relativism', hint: 'Context' },
      { difficulty: 'hard', word: 'Detachment', hint: 'Distance' },
      { difficulty: 'hard', word: 'Impermanence', hint: 'Change' },
      { difficulty: 'hard', word: 'Catharsis', hint: 'Release' },
      { difficulty: 'easy', word: 'Camaraderie', hint: 'Team' },
      { difficulty: 'easy', word: 'Success', hint: 'Win' },
      { difficulty: 'easy', word: 'Achievement', hint: 'Accomplish' },
      { difficulty: 'easy', word: 'Teamwork', hint: 'Cooperate' },
      { difficulty: 'easy', word: 'Unity', hint: 'Together' },
      { difficulty: 'medium', word: 'Prestige', hint: 'Status' },
      { difficulty: 'medium', word: 'Influence', hint: 'Sway' },
      { difficulty: 'medium', word: 'Determination', hint: 'Resolve' },

    ]
      },
  {
    id: 'minecraftMobs',
    name: 'Minecraft Mobs',
    entries: [
      { difficulty: 'easy', word: 'Zombie' },
      { difficulty: 'easy', word: 'Creeper' },
      { difficulty: 'easy', word: 'Skeleton' },
      { difficulty: 'easy', word: 'Spider' },
      { difficulty: 'easy', word: 'Pig' },
      { difficulty: 'easy', word: 'Cow' },
      { difficulty: 'easy', word: 'Sheep' },
      { difficulty: 'easy', word: 'Chicken' },
      { difficulty: 'easy', word: 'Wolf' },
      { difficulty: 'easy', word: 'Ocelot' },
      { difficulty: 'easy', word: 'Horse' },
      { difficulty: 'easy', word: 'Villager' },
      { difficulty: 'easy', word: 'Iron Golem' },
      { difficulty: 'easy', word: 'Snow Golem' },
      { difficulty: 'easy', word: 'Enderman' },
      { difficulty: 'medium', word: 'Witch' },
      { difficulty: 'medium', word: 'Blaze' },
      { difficulty: 'medium', word: 'Slime' },
      { difficulty: 'medium', word: 'Drowned' },
      { difficulty: 'medium', word: 'Pillager' },
      { difficulty: 'medium', word: 'Ghast' },
      { difficulty: 'medium', word: 'Magma Cube' },
      { difficulty: 'medium', word: 'Phantom' },
      { difficulty: 'medium', word: 'Vex' },
      { difficulty: 'medium', word: 'Allay' },
      { difficulty: 'medium', word: 'Warden' },
      { difficulty: 'medium', word: 'Hoglin' },
      { difficulty: 'medium', word: 'Piglin' },
      { difficulty: 'medium', word: 'Strider' },
      { difficulty: 'medium', word: 'Camel' },
      { difficulty: 'medium', word: 'Llama' },
      { difficulty: 'medium', word: 'Trader Llama' },
      { difficulty: 'medium', word: 'Fox' },
      { difficulty: 'medium', word: 'Bee' },
      { difficulty: 'medium', word: 'Goat' },
      { difficulty: 'medium', word: 'Turtle' },
      { difficulty: 'medium', word: 'Dolphin' },
      { difficulty: 'medium', word: 'Squid' },
      { difficulty: 'medium', word: 'Glow Squid' },
      { difficulty: 'medium', word: 'Panda' },
      { difficulty: 'medium', word: 'Polar Bear' },
      { difficulty: 'medium', word: 'Cat' },
      { difficulty: 'medium', word: 'Ender Dragon' },
      { difficulty: 'medium', word: 'Wither' },
      { difficulty: 'medium', word: 'Shulker' },
      { difficulty: 'medium', word: 'Ravager' },
      { difficulty: 'medium', word: 'Wither Skeleton' },
      { difficulty: 'medium', word: 'Guardian' },
      { difficulty: 'medium', word: 'Evoker' },
      { difficulty: 'medium', word: 'Bat' },
      { difficulty: 'medium', word: 'Mooshroom' },
      { difficulty: 'medium', word: 'Axolotl' },
      { difficulty: 'medium', word: 'Silverfish' },
      { difficulty: 'medium', word: 'Endermite' },
      { difficulty: 'medium', word: 'Chicken Jockey' },
      { difficulty: 'medium', word: 'Spider Jockey' },
      { difficulty: 'medium', word: 'Breeze' },
      { difficulty: 'medium', word: 'Wandering Trader' },
      { difficulty: 'medium', word: 'Elder Guardian' },
      { difficulty: 'medium', word: 'Skeleton Horse' },
      { difficulty: 'medium', word: 'Pufferfish' },
      { difficulty: 'medium', word: 'Frog' },
      { difficulty: 'medium', word: 'Zombie Horse' },
      { difficulty: 'medium', word: 'Illusioner' },
    ]
      },
  {
    id: 'minecraftBlocks',
    name: 'Minecraft Blocks',
    entries: [
      { difficulty: 'easy', word: 'Dirt Block' },
      { difficulty: 'easy', word: 'Stone Block' },
      { difficulty: 'easy', word: 'Oak Planks' },
      { difficulty: 'easy', word: 'Glass Block' },
      { difficulty: 'easy', word: 'Crafting Table' },
      { difficulty: 'easy', word: 'Sand Block' },
      { difficulty: 'easy', word: 'Gravel Block' },
      { difficulty: 'easy', word: 'Cobblestone' },
      { difficulty: 'easy', word: 'Oak Log' },
      { difficulty: 'easy', word: 'Birch Log' },
      { difficulty: 'easy', word: 'Spruce Log' },
      { difficulty: 'easy', word: 'Torch' },
      { difficulty: 'easy', word: 'Ladder' },
      { difficulty: 'easy', word: 'Mushroom' },
      { difficulty: 'easy', word: 'Cobweb' },
      { difficulty: 'easy', word: 'Spawner' },
      { difficulty: 'easy', word: 'Cake' },
      { difficulty: 'easy', word: 'Flower' },
      { difficulty: 'easy', word: 'Chest' },
      { difficulty: 'easy', word: 'Snow Block' },
      { difficulty: 'easy', word: 'Clay Block' },
      { difficulty: 'easy', word: 'Melon Block' },
      { difficulty: 'easy', word: 'Pumpkin' },
      { difficulty: 'easy', word: 'Jack o Lantern' },
      { difficulty: 'easy', word: 'Fence' },
      { difficulty: 'easy', word: 'Fence Gate' },
      { difficulty: 'easy', word: 'Wooden Door' },
      { difficulty: 'easy', word: 'Trapdoor' },
      { difficulty: 'easy', word: 'Pressure Plate' },
      { difficulty: 'easy', word: 'Button' },
      { difficulty: 'easy', word: 'Sign' },
      { difficulty: 'easy', word: 'Item Frame' },
      { difficulty: 'easy', word: 'Campfire' },
      { difficulty: 'easy', word: 'Coal Block' },
      { difficulty: 'easy', word: 'Painting' },
      { difficulty: 'easy', word: 'Carpet' },
      { difficulty: 'easy', word: 'Rail' },
      { difficulty: 'easy', word: 'Minecart' },
      { difficulty: 'easy', word: 'Boat' },
      { difficulty: 'easy', word: 'Wool Block' },
      { difficulty: 'easy', word: 'Leaf Block' },
      { difficulty: 'easy', word: 'Vines' },
      { difficulty: 'easy', word: 'Sugar Cane' },
      { difficulty: 'easy', word: 'Cactus' },
      { difficulty: 'easy', word: 'Bed' },
      { difficulty: 'medium', word: 'Magma Block' },
      { difficulty: 'medium', word: 'Glowstone' },
      { difficulty: 'medium', word: 'Iron Block' },
      { difficulty: 'medium', word: 'Gold Block' },
      { difficulty: 'medium', word: 'Diamond Block' },
      { difficulty: 'medium', word: 'Emerald Block' },
      { difficulty: 'medium', word: 'Anvil' },
      { difficulty: 'medium', word: 'Beacon' },
      { difficulty: 'medium', word: 'Slime Block' },
      { difficulty: 'medium', word: 'Honey Block' },
      { difficulty: 'medium', word: 'TNT' },
      { difficulty: 'medium', word: 'Nether Bricks' },
      { difficulty: 'medium', word: 'Basalt' },
      { difficulty: 'medium', word: 'Bricks' },
      { difficulty: 'medium', word: 'Ice Block' },
      { difficulty: 'medium', word: 'Bone Block' },
      { difficulty: 'medium', word: 'Dripstone' },
      { difficulty: 'medium', word: 'Ender Chest' },
      { difficulty: 'medium', word: 'Furnace' },
      { difficulty: 'medium', word: 'Obsidian' },
      { difficulty: 'medium', word: 'Bookshelf' },
      { difficulty: 'medium', word: 'Redstone Lamp' },
      { difficulty: 'medium', word: 'Hay Bale' },
      { difficulty: 'medium', word: 'Iron Bars' },
      { difficulty: 'medium', word: 'Chain' },
      { difficulty: 'medium', word: 'Lantern' },
      { difficulty: 'medium', word: 'Soul Lantern' },
      { difficulty: 'medium', word: 'Blast Furnace' },
      { difficulty: 'medium', word: 'Smoker' },
      { difficulty: 'medium', word: 'Cartography Table' },
      { difficulty: 'medium', word: 'Netherrack' },
      { difficulty: 'medium', word: 'Soul Sand' },
      { difficulty: 'medium', word: 'Blackstone' },
      { difficulty: 'medium', word: 'Sea Lantern' },
      { difficulty: 'medium', word: 'End Rod' },
      { difficulty: 'medium', word: 'Chorus Plant' },
      { difficulty: 'medium', word: 'Terracotta' },
      { difficulty: 'medium', word: 'Fletching Table' },
      { difficulty: 'medium', word: 'Smithing Table' },
      { difficulty: 'medium', word: 'Grindstone' },
      { difficulty: 'medium', word: 'Stonecutter' },
      { difficulty: 'medium', word: 'Composter' },
      { difficulty: 'medium', word: 'Barrel' },
      { difficulty: 'medium', word: 'Target Block' },
      { difficulty: 'medium', word: 'Observer' },
      { difficulty: 'medium', word: 'Dispenser' },
      { difficulty: 'medium', word: 'Dropper' },
      { difficulty: 'medium', word: 'Piston' },
      { difficulty: 'medium', word: 'Sticky Piston' },
      { difficulty: 'medium', word: 'Cauldron' },
      { difficulty: 'medium', word: 'Ancient Debris' },
      { difficulty: 'medium', word: 'Respawn Anchor' },
      { difficulty: 'medium', word: 'Enchanting Table' },
      { difficulty: 'medium', word: 'End Portal Frame' },
      { difficulty: 'medium', word: 'Netherite Block' },
      { difficulty: 'medium', word: 'Shulker Box' },
      { difficulty: 'medium', word: 'Dragon Egg' },
      { difficulty: 'medium', word: 'End Stone' },
      { difficulty: 'medium', word: 'Wither Skeleton Skull' },
      { difficulty: 'hard', word: 'Purpur Block' },
      { difficulty: 'hard', word: 'Conduit' },
      { difficulty: 'hard', word: 'Lodestone' },
      { difficulty: 'hard', word: 'Sculk Shrieker' },
      { difficulty: 'hard', word: 'Reinforced Deepslate' },
      { difficulty: 'hard', word: 'Crying Obsidian' },
    ]
      },
];

const difficulties = ['easy', 'medium', 'hard'];

function randomFrom(list) {
  if (!list?.length) return '';
  return list[Math.floor(Math.random() * list.length)];
}

export function listCategories() {
  return wordDatabase.map((category) => ({ id: category.id, label: category.name }));
}

export function listDifficulties() {
  return difficulties.map((id) => ({ id, label: id.charAt(0).toUpperCase() + id.slice(1) }));
}

export function pickWord(categoryIds, difficultyIds) {
  const allowedDifficulties = Array.isArray(difficultyIds)
    ? difficultyIds.filter(Boolean)
    : difficultyIds
    ? [difficultyIds]
    : [];
  const allowed = categoryIds?.length
    ? wordDatabase.filter((c) => categoryIds.includes(c.id))
    : wordDatabase;
  const categoryPool = allowed.length ? allowed : wordDatabase;
  const category = randomFrom(categoryPool) || wordDatabase[0];
  const filtered =
    category?.entries.filter((entry) => {
      if (!allowedDifficulties.length) return false;
      return allowedDifficulties.includes(entry.difficulty);
    }) || [];
  const pool = filtered.length ? filtered : category.entries;
  const entry = pool.length ? randomFrom(pool) : { word: 'Mystery' };
  const sameHintPool = categoryPool
    .flatMap((cat) => cat.entries.filter((e) => e.hint === entry.hint).map((e) => e.word))
    .filter((w) => w && w !== entry.word);
  const fallbackPool = pool.map((item) => item.word).filter((word) => word && word !== entry.word);
  const altPool = sameHintPool.length ? sameHintPool : fallbackPool;
  const imposterWord = randomFrom(altPool) || `${entry.word}*`;
  return {
    word: entry.word,
    imposterWord,
    hint: entry.hint || '',
    categoryName: category.name,
  };
}
